#!/usr/bin/env bun
/**
 * Downloads all item/NPC/mob/boss sprites from the Official Terraria Wiki
 * and saves them to ios/TerraWiki/Resources/Sprites.xcassets-like directory.
 *
 * Uses verified image filenames from the generated JSON databases.
 * Run after generate-items.mjs and generate-catalogs.mjs.
 *
 * Usage: bun scripts/download-sprites.mjs
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const spriteDir = join(root, "ios", "TerraWiki", "Resources", "Sprites");
mkdirSync(spriteDir, { recursive: true });

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// Collect all unique image filenames
const imageFiles = new Set();

function addImages(path, count) {
  try {
    const data = JSON.parse(readFileSync(path, "utf8"));
    const arr = Array.isArray(data) ? data : [data];
    for (const entry of arr) {
      const img = entry.image;
      if (img && img.endsWith(".png")) imageFiles.add(img);
    }
    console.log(`  ${path.split("/").pop()}: found ${count || arr.filter(e => e.image).length} images`);
  } catch { /* skip */ }
}

// Load all databases
const items = JSON.parse(readFileSync(join(root, "ios/TerraWiki/Resources/items.json"), "utf8"));
items.forEach(it => { if (it.image) imageFiles.add(it.image); });
console.log(`items.json: ${items.filter(i => i.image).length} images`);

addImages(join(root, "ios/TerraWiki/Resources/npcs.json"));
addImages(join(root, "ios/TerraWiki/Resources/mobs.json"));
addImages(join(root, "ios/TerraWiki/Resources/bosses.json"));

console.log(`\nTotal unique images to download: ${imageFiles.size}`);

// Download with checkpointing
const checkpointPath = join(spriteDir, ".checkpoint.json");
let done = existsSync(checkpointPath) ? new Set(JSON.parse(readFileSync(checkpointPath, "utf8"))) : new Set();

const pending = [...imageFiles].filter(f => !done.has(f));
console.log(`Already downloaded: ${done.size}, pending: ${pending.length}`);

const MAX_PER_RUN = 1000; // Limit to avoid timeout
const batch = pending.slice(0, MAX_PER_RUN);

for (let i = 0; i < batch.length; i++) {
  const file = batch[i];
  const localPath = join(spriteDir, file);

  if (existsSync(localPath)) { done.add(file); continue; }

  const url = `https://terraria.wiki.gg/wiki/Special:FilePath/${encodeURIComponent(file)}?width=128`;
  
  try {
    const res = await fetch(url);
    if (!res.ok) {
      if (res.status === 429) {
        console.log(`  rate-limited at ${i}/${batch.length}; waiting 5s`);
        await sleep(5000);
        i--; // retry
        continue;
      }
      done.add(file); // mark as "tried" even if failed
      continue;
    }
    const buf = Buffer.from(await res.arrayBuffer());
    // Ensure subdirectory exists
    const subdir = dirname(localPath);
    mkdirSync(subdir, { recursive: true });
    writeFileSync(localPath, buf);
    done.add(file);
  } catch (e) {
    console.log(`  error: ${file}: ${e.message}`);
  }

  if (i % 100 === 0 && i > 0) {
    console.log(`  ${i}/${batch.length} (total done: ${done.size})`);
    writeFileSync(checkpointPath, JSON.stringify([...done]));
  }
  await sleep(100); // 100ms between requests
}

writeFileSync(checkpointPath, JSON.stringify([...done]));
console.log(`Done: ${done.size} total images.`);

// Create the swift asset helper
const assetHelper = `// Auto-generated by download-sprites.mjs
// Maps image filename (e.g. "Iron Pickaxe.png") to bundled sprite name.
// Total sprites: ${done.size}

import SwiftUI

func bundledSprite(_ filename: String) -> Image? {
    // Strip extension for asset catalog lookup
    let name = filename.replacingOccurrences(of: ".png", with: "")
    // Check if UIImage can load it from the bundle
    guard let _ = UIImage(named: name) else { return nil }
    return Image(name)
}
`;

writeFileSync(join(root, "ios/TerraWiki/Sprites.swift"), assetHelper);
console.log("Updated Sprites.swift");